// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAWKmBgZ-jB8xU4DdJS_UYQ9Bqy_bPai4',
    appId: '1:642670173941:web:70de7cc89c001939d1efbc',
    messagingSenderId: '642670173941',
    projectId: 'connectcall-220b4',
    authDomain: 'connectcall-220b4.firebaseapp.com',
    storageBucket: 'connectcall-220b4.firebasestorage.app',
    measurementId: 'G-EQHG8Y4RE1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV604OMUATtFxqgFuZ0r4orgZFoXWo-5A',
    appId: '1:642670173941:android:561dab3761a63028d1efbc',
    messagingSenderId: '642670173941',
    projectId: 'connectcall-220b4',
    storageBucket: 'connectcall-220b4.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmRIBmipko5QZ3A-onX9luLUw1AX0dngU',
    appId: '1:642670173941:ios:d918d2d53b4bbf6fd1efbc',
    messagingSenderId: '642670173941',
    projectId: 'connectcall-220b4',
    storageBucket: 'connectcall-220b4.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmRIBmipko5QZ3A-onX9luLUw1AX0dngU',
    appId: '1:642670173941:ios:d918d2d53b4bbf6fd1efbc',
    messagingSenderId: '642670173941',
    projectId: 'connectcall-220b4',
    storageBucket: 'connectcall-220b4.firebasestorage.app',
    iosBundleId: 'com.example.connectCall',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBAWKmBgZ-jB8xU4DdJS_UYQ9Bqy_bPai4',
    appId: '1:642670173941:web:3f1b9368affcc5fbd1efbc',
    messagingSenderId: '642670173941',
    projectId: 'connectcall-220b4',
    authDomain: 'connectcall-220b4.firebaseapp.com',
    storageBucket: 'connectcall-220b4.firebasestorage.app',
    measurementId: 'G-LD7FHZ61XY',
  );
}
